### ISSUE TITLE
WebStatusCustom.cs

### ISSUE THREAD

**Issue by ghost** [felladrin/last-wish#4]
Shard Age reset to Zero after restart and is not working. Uptime is higher then Shard Age.
My system runs on ubuntu 14.04 machine.

Output in Browser:
Shard Age: 0 days, 0 hours and 0 minutes
Total Game Time: 0 hours and 2 minutes
Last Restart: 1/27/2016 3:51:16 PM
Uptime: 0 days, 0 hours and 23 minutes

Output in Browser after restart and waiting for some minutes.
Shard Age: 0 days, 0 hours and 0 minutes
Total Game Time: 0 hours and 2 minutes
Last Restart: 1/27/2016 4:15:59 PM
Uptime: 0 days, 0 hours and 7 minutes

**Comment by ghost** [comment]
my mistake,
servermachine time setting issue...
sorry

**Comment by felladrin** [comment]
Sure, no problem!
Thanks for using it!
